version: '3.1'

services:
  database:
    image: postgres
    environment:
      POSTGRES_PASSWORD: asm.botdb172
      POSTGRES_USERNAME: postgres
      POSTGRES_DB: asmbot
    ports:
      - 127.0.0.1:5433:5432
    env_file:
      - .env
